version: '3.8'

services:
  app:
    image: openjdk:21
    container_name: springboot-app
    volumes:
      - .:/app
      - ./src/main/resources/application.properties:/app/src/main/resources/application.properties
    working_dir: /app
    command: mvn spring-boot:run
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      MAVEN_VERSION: 3.9.9
    build:
      context: .
      dockerfile: Dockerfile

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
